"""Build the Claude Desktop one-click bundle (`klarpdf.mcpb`) from this checkout.

Run it from anywhere::

    python packaging/mcpb/build_mcpb.py            # -> dist/klarpdf-<version>.mcpb
    python packaging/mcpb/build_mcpb.py --validate # manifest + generated pyproject only, no pack

The bundle is a **release artifact, not a committed file** — the same treatment `dist/` gets for the
installer. What *is* committed is this script, `manifest.json`, and the generated
`pyproject.toml` beside it, so the inputs are reviewable and the output is reproducible.

**What goes in.** `server/` holds the bridge and the GUI-free core it stands on — `mcp_bridge/`,
`model/`, `util/`, `version.py` — plus a `pyproject.toml` naming its dependencies and the `uv.lock`
that pins and hashes them. Nothing else: no PySide6, no `viewer/`, no tests. It is the same package
boundary `pyproject.toml`'s `[tool.setuptools] packages` draws, for the same reason.

**Why the lock ships (M129).** `uv run --directory` **honours a committed `uv.lock`** — measured by
shipping one with `colorama` deliberately pinned a version back and watching that older version get
installed where a fresh resolve picks the newer. Without it the bundle carries pins only, uv writes
its own lock on the user's machine, and the hashes attest to whatever PyPI served at that moment.
With it, a Desktop install resolves from a lock we wrote and audit. The lock also covers what
`requirements-mcp.txt` structurally cannot: that file is deliberately platform-marker-free, so it can
never name `colorama` or `pywin32`, while the `uv.lock` pins and hashes them.

**What stays out, and why the format says so.** No `server/lib/`, no `server/venv/`. MCPB cannot
portably vendor compiled dependencies and this bundle has two of them (PyMuPDF is C, pydantic is
Rust), so a vendored bundle would be one-platform-per-file. `uv` resolves them per machine instead,
which is what lets a single file serve macOS, Windows and Linux.

**The `server.type` story, corrected 2026-08-12.** PLAN.md specified `server.type = "uv"`. That type
does not exist: `mcpb` 2.1.2 validates `server.type` against exactly `python | node | binary`, on
every manifest version it accepts (0.1/0.2/0.3 — 1.0 and above are rejected outright). The bundle
therefore declares the supported `python` type while its `mcp_config.command` **is** `uv`, which
preserves every property the original decision was made for — resolve-at-install, no vendoring, one
file for all three platforms — and changes exactly one thing: `uv` must be on the user's PATH,
because the host is no longer the thing supplying it. That prerequisite is in `mcp_bridge/README.md`.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
LOCK = ROOT / "requirements-mcp.txt"
MANIFEST = HERE / "manifest.json"
GENERATED_PYPROJECT = HERE / "pyproject.toml"
UV_LOCK = HERE / "uv.lock"

# The bridge plus the Qt-free core it imports. Mirrors pyproject.toml's [tool.setuptools] packages.
PAYLOAD_PACKAGES = ("mcp_bridge", "model", "util")
PAYLOAD_MODULES = ("version.py",)

# model/edit_commands.py imports QUndoCommand. Nothing on the server path touches it (that is what
# tests/test_mcp_no_qt.py pins), but shipping it inside a bundle that deliberately has no PySide6
# would put an unimportable file in a user's install for no reason. Dropped here rather than left
# to be discovered.
EXCLUDE_FILES = {"model/edit_commands.py"}

_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*(?:\[[^\]]+\])?)==([^\s;#]+)")


def read_version() -> str:
    text = (ROOT / "version.py").read_text(encoding="utf-8")
    match = re.search(r'__version__\s*=\s*"([^"]+)"', text)
    if not match:
        raise SystemExit("could not read __version__ from version.py")
    return match.group(1)


def read_pins() -> list[str]:
    """Every `name==version` in the compiled MCP lock, in file order.

    The bundle pins the **whole transitive set**, not just the two direct dependencies. PLAN.md's
    reason: the `.mcpb` resolves online at install time, so two users installing a month apart
    must not end up with different transitive sets. Floors would allow exactly that.
    """
    if not LOCK.exists():
        raise SystemExit(f"{LOCK} is missing — run: pip-compile requirements-mcp.in -o {LOCK.name}")
    pins = []
    for line in LOCK.read_text(encoding="utf-8").splitlines():
        match = _PIN.match(line.strip())
        if match:
            pins.append(f"{match.group(1)}=={match.group(2)}")
    if not pins:
        raise SystemExit(f"no pins found in {LOCK}")
    return pins


def render_pyproject(version: str, pins: list[str]) -> str:
    deps = "\n".join(f'    "{pin}",' for pin in pins)
    return f'''# GENERATED by packaging/mcpb/build_mcpb.py from requirements-mcp.txt — do not hand-edit.
#
# This is the one place in the project where dependencies are *declared* rather than installed from
# a lock, and only because the MCPB format requires it: the bundle resolves online at install time,
# so the manifest of what to fetch has to travel with it. Every entry is an `==` pin covering the
# whole transitive set, so two users installing a month apart get the same environment.
#
# NOTE: what this file installs is NOT covered by the repo's pip-audit steps, which audit
# requirements-mcp.txt on the pip/pipx path. It is generated *from* that lock, so the two agree at
# build time — but a Desktop install resolves fresh (PLAN.md §Dependencies & packaging).
[project]
name = "klarpdf-mcp"
version = "{version}"
description = "KlarPDF's PDF engine as MCP tools — read, transform, verifiably redact. Offline."
requires-python = ">=3.12,<3.13"
dependencies = [
{deps}
]

[project.scripts]
klarpdf-mcp = "mcp_bridge.server:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mcp_bridge", "model", "util"]
py-modules = ["version"]
'''


def stage(target: Path, version: str, pins: list[str]) -> Path:
    """Assemble the bundle directory: manifest + server payload + generated pyproject."""
    if target.exists():
        shutil.rmtree(target)
    server = target / "server"
    server.mkdir(parents=True)

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    manifest["version"] = version  # single source of truth stays version.py
    (target / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    for package in PAYLOAD_PACKAGES:
        shutil.copytree(
            ROOT / package,
            server / package,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "README.md"),
        )
    for module in PAYLOAD_MODULES:
        shutil.copy2(ROOT / module, server / module)
    for relative in EXCLUDE_FILES:
        dropped = server / relative
        if dropped.exists():
            dropped.unlink()

    (server / "pyproject.toml").write_text(render_pyproject(version, pins), encoding="utf-8")

    # The lock travels with the bundle, and it is the reason the Desktop install is hash-verified.
    # Measured in M129: `uv run --directory` honours a committed `uv.lock` — a bundle shipped with
    # colorama deliberately pinned one version back installed that older version, where a fresh
    # resolve picks the newer one. Without this copy the bundle carries only `pyproject.toml`, uv
    # writes its own lock on the user's machine, and the hashes attest to whatever PyPI served at
    # that moment rather than to anything we audited.
    if not UV_LOCK.exists():
        raise SystemExit(
            f"{UV_LOCK} is missing — the bundle must ship its lock.\n"
            f"  Regenerate it:  cd {UV_LOCK.parent}  &&  uv lock"
        )
    shutil.copy2(UV_LOCK, server / "uv.lock")

    for forbidden in ("lib", "venv"):
        assert not (server / forbidden).exists(), f"the format forbids server/{forbidden}/"
    return target


def resolve_npx() -> str:
    """Full path to the `npx` launcher, because the bare name does not start one on Windows.

    npm ships `npx` as `npx.CMD` there, and `CreateProcess` — which is what `subprocess` calls with
    a list argv — searches PATH appending only `.exe`. It never consults `PATHEXT`, so the bare
    "npx" that works on Linux and macOS raises `FileNotFoundError: [WinError 2]` on the one platform
    this project ships. `shutil.which` does consult `PATHEXT` and hands back a name CreateProcess
    can actually start. (Measured 2026-08-27: bare "npx" fails, `shutil.which("npx")` ->
    `...\\node\\npx.CMD` runs.)
    """
    found = shutil.which("npx")
    if found is None:
        raise SystemExit(
            "npx is not on PATH — the mcpb CLI is a Node tool and this build shells out to it.\n"
            "  Install Node (https://nodejs.org), open a new shell so PATH is refreshed, re-run.\n"
            "  Nothing the bundle does at runtime needs Node; it is a build-time dependency only."
        )
    return found


def mcpb(*args: str) -> subprocess.CompletedProcess:
    """Run the mcpb CLI via npx (it is a Node tool; nothing here depends on it at runtime)."""
    return subprocess.run(
        [resolve_npx(), "--yes", "@anthropic-ai/mcpb@latest", *args],
        capture_output=True,
        text=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--validate",
        action="store_true",
        help="regenerate the pyproject and validate the manifest; do not pack",
    )
    parser.add_argument("--out", default=str(ROOT / "dist"), help="output directory")
    args = parser.parse_args()

    version = read_version()
    pins = read_pins()

    # Keep the committed copy in step with the lock, so a reviewer reads the same thing the build
    # ships and a stale pyproject cannot be released by accident.
    GENERATED_PYPROJECT.write_text(render_pyproject(version, pins), encoding="utf-8")
    print(f"pyproject.toml regenerated from {LOCK.name} ({len(pins)} pinned packages)")

    result = mcpb("validate", str(MANIFEST))
    print(result.stdout.strip() or result.stderr.strip())
    if result.returncode != 0:
        return result.returncode
    if args.validate:
        return 0

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    staged = stage(out_dir / "mcpb-stage", version, pins)
    bundle = out_dir / f"klarpdf-{version}.mcpb"
    result = mcpb("pack", str(staged), str(bundle))
    print(result.stdout.strip() or result.stderr.strip())
    if result.returncode != 0:
        return result.returncode
    print(f"\nbuilt {bundle} ({bundle.stat().st_size / 1024:.0f} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
